import { IKingdom, IKingdomWithFullSongs } from "@/interfaces/api/kingdom";

export const MOCK_KINGDOMS: IKingdomWithFullSongs[] = [
  {
    id: "k-001",
    name: "Vale das Primeiras Notas",
    description:
      "Um vale sereno onde o vento sussurra melodias antigas. É aqui que toda jornada começa — com silêncio, e a coragem de romper com ele.",
    ambience: "Tranquilo, esperançoso, acolhedor",
    visual_elements: ["flores silvestres", "riachos suaves", "névoa matinal"],
    keywords: ["início", "coragem", "despertar"],
    identity: "O reino do primeiro passo",
    image_url: null,
    level: 1,
    base_difficulty_range: [1, 3],
    boss_id: null,
    relic_id: null,
    categories: ["classica", "folk"],
    created_at: new Date().toISOString(),
    lore: {
      part_1: {
        title: "O Chamado",
        content:
          "Dizem que o vale floresce apenas quando alguém decide tocar pela primeira vez. As flores antigas guardam nas pétalas o eco de cada nota já tocada neste lugar sagrado. Você sente o peso do silêncio — e a urgência de preenchê-lo.",
      },
      part_2: {
        title: "A Névoa da Dúvida",
        content:
          "Uma névoa espessa cobre o caminho, feita dos 'e se eu não for bom o suficiente'. Ela sussurra que outros são mais talentosos, que é tarde demais, que a música não é para você. Mas o riacho à sua frente continua cantando — indiferente às suas dúvidas.",
      },
      part_3: {
        title: "O Riacho da Prática",
        content:
          "Cada nota tocada alimenta o riacho. Cada dia praticado abre novos caminhos por entre as pedras. O segredo que os antigos bardos guardavam: a consistência transforma água em ouro, silêncio em sinfonia.",
      },
      final_part: {
        title: "O Encontro",
        content:
          "No coração do vale, onde as águas convergem, a Voz do Silêncio aguarda. Não para destruir — mas para ser enfrentada com a única arma que existe: sua música. Imperfeita, trêmula, mas genuinamente sua.",
      },
    },
    songs: {
      part_1: "s-001-1",
      part_2: "s-001-2",
      part_3: "s-001-3",
      final_part: "s-001-boss",
    },
    songs_parts: {
      part_1: {
        id: "s-001-1",
        created_at: new Date().toISOString(),
        title: "Clair de Lune",
        difficulty: "easy",
        xp_reward: 100,
        kingdom_id: "k-001",
        is_boss: false,
        artist: "Claude Debussy",
        version_tag: "1.0",
        sheet_music_url: "https://sheets.example.com/debussy-clair-de-lune",
      },
      part_2: {
        id: "s-001-2",
        created_at: new Date().toISOString(),
        title: "River Flows in You",
        difficulty: "easy",
        xp_reward: 120,
        kingdom_id: "k-001",
        is_boss: false,
        artist: "Yiruma",
        version_tag: "1.0",
        sheet_music_url: "https://sheets.example.com/yiruma-river-flows",
      },
      part_3: {
        id: "s-001-3",
        created_at: new Date().toISOString(),
        title: "Gymnopédie No.1",
        difficulty: "medium",
        xp_reward: 150,
        kingdom_id: "k-001",
        is_boss: false,
        artist: "Erik Satie",
        version_tag: "1.0",
        sheet_music_url: "https://sheets.example.com/satie-gymnopédie",
      },
      final_part: {
        id: "s-001-boss",
        created_at: new Date().toISOString(),
        title: "Moonlight Sonata",
        difficulty: "hard",
        xp_reward: 500,
        kingdom_id: "k-001",
        is_boss: true,
        artist: "Ludwig van Beethoven",
        version_tag: "1.0",
        sheet_music_url: "https://sheets.example.com/beethoven-moonlight",
      },
    },
  },
  {
    id: "k-002",
    name: "Floresta das Melodias Perdidas",
    description:
      "Uma floresta ancestral onde as árvores guardam fragmentos de músicas esquecidas. Quem se atreve a entrar, descobre ritmos que o mundo perdeu.",
    ambience: "Misterioso, encantador, melancólico",
    visual_elements: ["cogumelos luminosos", "raízes antigas", "vagalumes"],
    keywords: ["mistério", "ritmo", "memória"],
    identity: "O reino dos ritmos ancestrais",
    image_url: null,
    level: 2,
    base_difficulty_range: [3, 5],
    boss_id: null,
    relic_id: null,
    categories: ["games", "anime"],
    created_at: new Date().toISOString(),
    lore: {
      part_1: {
        title: "Sussurros das Raízes",
        content:
          "As raízes milenares carregam vibrações de músicos que passaram por aqui. Cada raiz é uma história — de quem tentou, de quem desistiu, de quem triunfou. Você coloca as mãos na casca áspera e sente o pulso da floresta.",
      },
      part_2: {
        title: "A Dança dos Vagalumes",
        content:
          "À noite, vagalumes formam partituras vivas no ar. Eles dançam em padrões que revelam segredos rítmicos impossíveis de anotar — só de sentir. Siga a luz mais brilhante.",
      },
      part_3: {
        title: "O Ritmo da Floresta",
        content:
          "A floresta tem seu próprio pulso, antigo como as estrelas. Sincronizar com ele é o segredo que separa os que tocam dos que realmente ouvem. Você começa a entender: a música não é criada. Ela é descoberta.",
      },
      final_part: {
        title: "O Guardião Desperta",
        content:
          "Nas profundezas, onde a luz dos vagalumes não chega, o Guardião do Esquecimento abre os olhos. Ele existe de toda nota não tocada, de toda música abandonada. Vencê-lo é provar que você não será mais um fantasma nesta floresta.",
      },
    },
    songs: {
      part_1: "s-002-1",
      part_2: "s-002-2",
      part_3: "s-002-3",
      final_part: "s-002-boss",
    },
    songs_parts: {
      part_1: {
        id: "s-002-1",
        created_at: new Date().toISOString(),
        title: "Zelda's Lullaby",
        difficulty: "medium",
        xp_reward: 150,
        kingdom_id: "k-002",
        is_boss: false,
        artist: "Koji Kondo",
        version_tag: "1.0",
        sheet_music_url: "https://sheets.example.com/kondo-zelda-lullaby",
      },
      part_2: {
        id: "s-002-2",
        created_at: new Date().toISOString(),
        title: "To Zanarkand",
        difficulty: "medium",
        xp_reward: 180,
        kingdom_id: "k-002",
        is_boss: false,
        artist: "Nobuo Uematsu",
        version_tag: "1.0",
        sheet_music_url: "https://sheets.example.com/uematsu-zanarkand",
      },
      part_3: {
        id: "s-002-3",
        created_at: new Date().toISOString(),
        title: "Aerith's Theme",
        difficulty: "hard",
        xp_reward: 200,
        kingdom_id: "k-002",
        is_boss: false,
        artist: "Nobuo Uematsu",
        version_tag: "1.0",
        sheet_music_url: "https://sheets.example.com/uematsu-aerith",
      },
      final_part: {
        id: "s-002-boss",
        created_at: new Date().toISOString(),
        title: "One-Winged Angel",
        difficulty: "hard",
        xp_reward: 600,
        kingdom_id: "k-002",
        is_boss: true,
        artist: "Nobuo Uematsu",
        version_tag: "1.0",
        sheet_music_url: "https://sheets.example.com/uematsu-one-winged",
      },
    },
  },
  {
    id: "k-003",
    name: "Cidadela das Cordas de Aço",
    description:
      "Uma fortaleza no topo de uma montanha de cristal. Seus habitantes acreditam que a técnica perfeita é a única forma de arte verdadeira.",
    ambience: "Grandioso, intimidador, imponente",
    visual_elements: ["torres cristalinas", "estandartes", "ventos gelados"],
    keywords: ["técnica", "disciplina", "grandeza"],
    identity: "O reino da maestria técnica",
    image_url: null,
    level: 3,
    base_difficulty_range: [5, 8],
    boss_id: null,
    relic_id: null,
    categories: ["classica"],
    created_at: new Date().toISOString(),
    lore: {
      part_1: {
        title: "As Torres do Julgamento",
        content:
          "Cada torre representa uma técnica diferente. Escalar todas é o desafio da cidadela. As paredes de cristal refletem seus erros com crueldade implacável — não há onde se esconder aqui.",
      },
      part_2: {
        title: "O Código das Cordas",
        content:
          "A cidadela tem leis rígidas gravadas em pedra: toda nota deve ser perfeita, ou não deve existir. Os habitantes olham com desdém para qualquer hesitação. Mas você começa a perceber — a perfeição deles é uma prisão.",
      },
      part_3: {
        title: "A Rebelião Silenciosa",
        content:
          "Nos subterrâneos, músicos sussurram entre si: 'A imperfeição também é arte'. Eles praticam às escondidas músicas que fazem chorar — imperfeitas, humanas, vivas. Você entende que técnica sem alma é apenas acrobacia.",
      },
      final_part: {
        title: "Lord Perfectionis",
        content:
          "No salão principal, sentado em um trono de partituras imaculadas, o Tirano aguarda. Ele usa sua própria voz para lembrar cada erro que você já cometeu. A resposta não é a perfeição — é tocar mesmo assim.",
      },
    },
    songs: {
      part_1: "s-003-1",
      part_2: "s-003-2",
      part_3: "s-003-3",
      final_part: "s-003-boss",
    },
    songs_parts: {
      part_1: {
        id: "s-003-1",
        created_at: new Date().toISOString(),
        title: "Maple Leaf Rag",
        difficulty: "hard",
        xp_reward: 250,
        kingdom_id: "k-003",
        is_boss: false,
        artist: "Scott Joplin",
        version_tag: "1.0",
        sheet_music_url: "https://sheets.example.com/joplin-maple-leaf",
      },
      part_2: {
        id: "s-003-2",
        created_at: new Date().toISOString(),
        title: "Hungarian Rhapsody No.2",
        difficulty: "hard",
        xp_reward: 300,
        kingdom_id: "k-003",
        is_boss: false,
        artist: "Franz Liszt",
        version_tag: "1.0",
        sheet_music_url: "https://sheets.example.com/liszt-rhapsody",
      },
      part_3: {
        id: "s-003-3",
        created_at: new Date().toISOString(),
        title: "Prelude in C Minor",
        difficulty: "hard",
        xp_reward: 280,
        kingdom_id: "k-003",
        is_boss: false,
        artist: "Frédéric Chopin",
        version_tag: "1.0",
        sheet_music_url: "https://sheets.example.com/chopin-prelude",
      },
      final_part: {
        id: "s-003-boss",
        created_at: new Date().toISOString(),
        title: "Flight of the Bumblebee",
        difficulty: "hard",
        xp_reward: 700,
        kingdom_id: "k-003",
        is_boss: true,
        artist: "Rimsky-Korsakov",
        version_tag: "1.0",
        sheet_music_url: "https://sheets.example.com/rimsky-bumblebee",
      },
    },
  },
];
